// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYFMEBSGplqrzYQqvcEYJmf15besXR-A',
    appId: '1:749572181125:web:1f0cdac359e4ccc0e8adec',
    messagingSenderId: '749572181125',
    projectId: 'art-gallery-44758',
    authDomain: 'art-gallery-44758.firebaseapp.com',
    storageBucket: 'art-gallery-44758.appspot.com',
    measurementId: 'G-CKC0HG7N3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4rG5EfjXldwx-JO5HkZ_6MX38uNwV4c',
    appId: '1:749572181125:android:48f01ded228430c3e8adec',
    messagingSenderId: '749572181125',
    projectId: 'art-gallery-44758',
    storageBucket: 'art-gallery-44758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySmAdLQdmNX5oeLNU8djcH2KkdUsa_F0',
    appId: '1:749572181125:ios:25843f2b2e05e1eee8adec',
    messagingSenderId: '749572181125',
    projectId: 'art-gallery-44758',
    storageBucket: 'art-gallery-44758.appspot.com',
    iosBundleId: 'com.example.minorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySmAdLQdmNX5oeLNU8djcH2KkdUsa_F0',
    appId: '1:749572181125:ios:25843f2b2e05e1eee8adec',
    messagingSenderId: '749572181125',
    projectId: 'art-gallery-44758',
    storageBucket: 'art-gallery-44758.appspot.com',
    iosBundleId: 'com.example.minorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsYFMEBSGplqrzYQqvcEYJmf15besXR-A',
    appId: '1:749572181125:web:7992ef08485667c0e8adec',
    messagingSenderId: '749572181125',
    projectId: 'art-gallery-44758',
    authDomain: 'art-gallery-44758.firebaseapp.com',
    storageBucket: 'art-gallery-44758.appspot.com',
    measurementId: 'G-VY2J3MV73C',
  );
}
